# Generated by Django 4.2.6 on 2023-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату картой'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('credit_card', 'Оплата картой')], max_length=150, null=True, verbose_name='способ оплаты'),
        ),
    ]
